//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EXAM
    {
        
        public int id { get; set; }

        [DisplayName("EXAM Subject")]
        public Nullable<int> examSubject { get; set; }

        [DisplayName("Start Time")]
        [Required(ErrorMessage = "Hãy nhập giờ bắt đầu")]
        [DataType(DataType.Time)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm}")]
        public System.DateTime startTime { get; set; }

        [DisplayName("EXAM Date")]
        [Required(ErrorMessage = "Hãy nhập ngày thi")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime examDate { get; set; }

        [DisplayName("EXAM Duration")]
        [Required(ErrorMessage = "Hãy nhập thời gian làm bài")]
        public int examDuration { get; set; }

        [DisplayName("Class Room")]
        public Nullable<int> classRoom { get; set; }

        [DisplayName("Falcuty")]
        public Nullable<int> faculty { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Faculty Faculty1 { get; set; }
    }
}
